### PR TITLE
fixes some link references

### PR DESCRIPTION
**Pull request by henderiw**
fixes some reference in the docs

### CODE REVIEW

**Comment by steiler** [comment]
Can you please clean up the PR. There is the `hook/__pychache__` folder with python artifacts... that do not belong there.

**Comment by henderiw** [comment]
fixed but I means we need to add git ignore files as this got created when running the makefile

**Comment by steiler** [comment]
Ok yes, go ahead and do so.

**Review by steiler — APPROVED** [review]
lgtm

**Pull request merged**
